export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_LOADING = "FETCH_BOOKS_LOADING";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";
export const REQUEST = "REQUEST";
export const ADDED_TO_CART = "ADDED_TO_CART"
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const DELETE_TO_CART = 'DELETE_TO_CART'
